channels:
  - defaults
dependencies:
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - inflection=0.5.1
  - jinja2=3.0.1
  - libcxx=10.0.0
  - libffi=3.3
  - markupsafe=2.0.1
  - ncurses=6.2
  - openssl=1.1.1m
  - pip=21.2.4
  - pyrsistent=0.18.0
  - python=3.9.6
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aiohttp==3.8.0
    - aiosignal==1.2.0
    - async-timeout==4.0.0
    - attrs==21.2.0
    - charset-normalizer==2.0.7
    - click==8.0.4
    - datasets==1.15.1
    - dill==0.3.4
    - filelock==3.3.2
    - frozenlist==1.2.0
    - fsspec==2021.11.0
    - huggingface-hub==0.1.2
    - idna==3.3
    - joblib==1.1.0
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - numpy==1.21.4
    - packaging==21.2
    - pandas==1.3.4
    - pyarrow==6.0.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.26.0
    - sacremoses==0.0.49
    - six==1.16.0
    - tokenizers==0.11.6
    - tqdm==4.62.3
    - transformers==4.17.0
    - tree-sitter==0.19.0
    - types-urllib3==1.26.11
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - xxhash==2.0.2
    - yarl==1.7.2
