channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - conda=4.13.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.7.3
  - cryptography=36.0.0
  - idna=3.3
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python.app=3
  - readline=8.1.2
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tqdm=4.62.3
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - inflection==0.5.1
    - mypy==0.961
    - mypy-extensions==0.4.3
    - nodeenv==1.7.0
    - pyright==1.1.260
    - setuptools==62.3.2
    - tapas-utaustin==0.0.1
    - tomli==2.0.1
    - tree-sitter==0.20.0
    - typing-extensions==4.3.0
