"""
This type stub file was generated by pyright.
"""

from numpy._pytesttester import PytestTester
from numpy import matrix as matrix
from numpy.matrixlib.defmatrix import asmatrix as asmatrix, bmat as bmat, mat as mat

__all__: list[str]
__path__: list[str]
test: PytestTester
