
# THIS FILE IS AUTOGENERATED
# CHANGES MAY BE LOST

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, TypeVar, Any, Generic, Union, Optional
from collections.abc import Callable

from abc import ABC, abstractmethod

S = TypeVar('S')
T = TypeVar('T')


class A(Generic[(T, S)]):
    pass