"""
This type stub file was generated by pyright.
"""

from numpy._pytesttester import PytestTester
from unittest import TestCase as TestCase
from numpy.testing._private.utils import HAS_LAPACK64 as HAS_LAPACK64, HAS_REFCOUNT as HAS_REFCOUNT, IS_PYPY as IS_PYPY, IS_PYSTON as IS_PYSTON, IgnoreException as IgnoreException, KnownFailureException as KnownFailureException, SkipTest as SkipTest, assert_ as assert_, assert_allclose as assert_allclose, assert_almost_equal as assert_almost_equal, assert_approx_equal as assert_approx_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_almost_equal_nulp as assert_array_almost_equal_nulp, assert_array_compare as assert_array_compare, assert_array_equal as assert_array_equal, assert_array_less as assert_array_less, assert_array_max_ulp as assert_array_max_ulp, assert_equal as assert_equal, assert_no_gc_cycles as assert_no_gc_cycles, assert_no_warnings as assert_no_warnings, assert_raises as assert_raises, assert_raises_regex as assert_raises_regex, assert_string_equal as assert_string_equal, assert_warns as assert_warns, break_cycles as break_cycles, build_err_msg as build_err_msg, clear_and_catch_warnings as clear_and_catch_warnings, decorate_methods as decorate_methods, jiffies as jiffies, measure as measure, memusage as memusage, print_assert_equal as print_assert_equal, raises as raises, rundocs as rundocs, runstring as runstring, suppress_warnings as suppress_warnings, tempdir as tempdir, temppath as temppath, verbose as verbose

__all__: list[str]
__path__: list[str]
test: PytestTester
def run_module_suite(file_to_run: None | str = ..., argv: None | list[str] = ...) -> None:
    ...

