"""
This type stub file was generated by pyright.
"""

import ctypes as ct
from typing import Any, Generic, TypeVar, overload
from numpy import ndarray
from numpy.ctypeslib import c_intp

_CastT = TypeVar("_CastT", bound=ct._CanCastTo)
_CT = TypeVar("_CT", bound=ct._CData)
_PT = TypeVar("_PT", bound=None | int)
class _ctypes(Generic[_PT]):
    @overload
    def __new__(cls, array: ndarray[Any, Any], ptr: None = ...) -> _ctypes[None]:
        ...
    
    @overload
    def __new__(cls, array: ndarray[Any, Any], ptr: _PT) -> _ctypes[_PT]:
        ...
    
    @property
    def data(self) -> _PT:
        ...
    
    @property
    def shape(self) -> ct.Array[c_intp]:
        ...
    
    @property
    def strides(self) -> ct.Array[c_intp]:
        ...
    
    def data_as(self, obj: type[_CastT]) -> _CastT:
        ...
    
    def shape_as(self, obj: type[_CT]) -> ct.Array[_CT]:
        ...
    
    def strides_as(self, obj: type[_CT]) -> ct.Array[_CT]:
        ...
    


