"""
This type stub file was generated by pyright.
"""

from ._array_object import Array
from typing import Optional, Tuple

def argmax(x: Array, /, *, axis: Optional[int] = ..., keepdims: bool = ...) -> Array:
    """
    Array API compatible wrapper for :py:func:`np.argmax <numpy.argmax>`.

    See its docstring for more information.
    """
    ...

def argmin(x: Array, /, *, axis: Optional[int] = ..., keepdims: bool = ...) -> Array:
    """
    Array API compatible wrapper for :py:func:`np.argmin <numpy.argmin>`.

    See its docstring for more information.
    """
    ...

def nonzero(x: Array, /) -> Tuple[Array, ...]:
    """
    Array API compatible wrapper for :py:func:`np.nonzero <numpy.nonzero>`.

    See its docstring for more information.
    """
    ...

def where(condition: Array, x1: Array, x2: Array, /) -> Array:
    """
    Array API compatible wrapper for :py:func:`np.where <numpy.where>`.

    See its docstring for more information.
    """
    ...

