"""
This type stub file was generated by pyright.
"""

from ._array_object import Array
from typing import NamedTuple

class UniqueAllResult(NamedTuple):
    values: Array
    indices: Array
    inverse_indices: Array
    counts: Array
    ...


class UniqueCountsResult(NamedTuple):
    values: Array
    counts: Array
    ...


class UniqueInverseResult(NamedTuple):
    values: Array
    inverse_indices: Array
    ...


def unique_all(x: Array, /) -> UniqueAllResult:
    """
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.

    See its docstring for more information.
    """
    ...

def unique_counts(x: Array, /) -> UniqueCountsResult:
    ...

def unique_inverse(x: Array, /) -> UniqueInverseResult:
    """
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.

    See its docstring for more information.
    """
    ...

def unique_values(x: Array, /) -> Array:
    """
    Array API compatible wrapper for :py:func:`np.unique <numpy.unique>`.

    See its docstring for more information.
    """
    ...

