"""
This type stub file was generated by pyright.
"""

from distutils.command.build_clib import build_clib as old_build_clib

""" Modified version of build_clib that handles fortran source files.
"""
_l = old_build_clib.user_options
class build_clib(old_build_clib):
    description = ...
    user_options = ...
    boolean_options = ...
    def initialize_options(self): # -> None:
        ...
    
    def finalize_options(self): # -> None:
        ...
    
    def have_f_sources(self): # -> bool:
        ...
    
    def have_cxx_sources(self): # -> bool:
        ...
    
    def run(self): # -> None:
        ...
    
    def get_source_files(self): # -> list[Unknown]:
        ...
    
    def build_libraries(self, libraries): # -> None:
        ...
    
    def assemble_flags(self, in_flags): # -> list[Unknown]:
        """ Assemble flags from flag list

        Parameters
        ----------
        in_flags : None or sequence
            None corresponds to empty list.  Sequence elements can be strings
            or callables that return lists of strings. Callable takes `self` as
            single parameter.

        Returns
        -------
        out_flags : list
        """
        ...
    
    def build_a_library(self, build_info, lib_name, libraries):
        ...
    


