"""
This type stub file was generated by pyright.
"""

from distutils.core import Command

class install_clib(Command):
    description = ...
    user_options = ...
    def initialize_options(self): # -> None:
        ...
    
    def finalize_options(self): # -> None:
        ...
    
    def run(self): # -> None:
        ...
    
    def get_outputs(self): # -> list[Unknown]:
        ...
    


