"""
This type stub file was generated by pyright.
"""

from distutils.command.install_data import install_data as old_install_data

have_setuptools = ...
class install_data(old_install_data):
    def run(self): # -> None:
        ...
    
    def finalize_options(self): # -> None:
        ...
    


